### ISSUE TITLE
RemoteRunnable unexpected behavior

### ISSUE THREAD

**Issue by imjwang** [langchain-ai/langchainjs#3347] opened 2023-11-20 03:21 UTC
Hi, I'm using langserve to host an OpenAI model like this:
```python
add_routes(app, ChatOpenAI(), path="/chat")
```
But I have been unable to use it like a typical model to create a chain:
```javascript
// This code runs on server side
const prompt = await pull("efriis/my-first-prompt");

// const model = new ChatOpenAI(); This works but below doesn't
const model = new RemoteRunnable({url: 'https://5f0a-34-67-137-88.ngrok.io/chat'})

const chain = RunnableSequence.from([prompt, model]);

const result = await chain.invoke({
  "profession": "biologist",
  "question": "What is special about parrots?",
});

console.log(result);
```

I'm getting this error.
```shell
INFO:     2601:641:300:8b50:70f8:6923:4bfd:6fb4:0 - "POST /chat/invoke HTTP/1.1" 422 Unprocessable Entity
```

It works as expected from python, you can use RemoteRunnable to create a chain.

Wondering if this is in the works or am i doing something wrong?

package.json:
```json
"langchain": "^0.0.193"
```

**Comment by jacoblee93** [comment] 2023-11-22 15:27
Thanks for the report!

@efriis can you have a look at this one?

**Comment by efriis** [comment] 2023-11-23 19:00
Thanks @imjwang ! I'll take a look at this next week after the US holiday. In the meantime, would recommend trying to upgrade your `langserve` and `langchain` python versions in your server! Because you're getting a 422, I would guess the issue is on the server side rather than the client.

**Comment by efriis** [comment] 2023-12-04 23:14
Closing this for now @imjwang ! Let me know if it turns out to be a RemoteRunnable issue instead of something in your LangServe-hosted chain.

**Closed by efriis** 2023-12-04 23:14 UTC
Labels: auto:bug
