### ISSUE TITLE
Retry logic for OpenAI timeouts

### ISSUE THREAD

**Issue by wcummings** [langchain-ai/langchainjs#2706] opened 2023-09-24 16:37 UTC
I'm seeing the following error in prod:

```
Error [TimeoutError]: Request timed out.
    at wrapOpenAIClientError (file:///app/node_modules/langchain/dist/util/openai.js:6:17)
    at file:///app/node_modules/langchain/dist/chat_models/openai.js:518:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/app/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 1,
  retriesLeft: 6
}
```

It's getting captured in my catch block, so I'm fairly sure the retries aren't happening, unless the first attempt is the one that gets re-thrown or something confusing like that. Is it possible this doesn't meet the criteria for retryable? Could this be addressed using the FailedAttemptHandler interface?

I've not set a timeout for the LLM. I'm having a hard time figuring out the default value.

```
  /**
   * Custom handler to handle failed attempts. Takes the originally thrown
   * error object as input, and should itself throw an error if the input
   * error is not retryable.
   */
  onFailedAttempt?: FailedAttemptHandler;
  ```

**Comment by wcummings** [comment] 2023-09-25 16:03
The default failure handler looks like the culprit:

```
const STATUS_NO_RETRY = [
  400, // Bad Request
  401, // Unauthorized
  402, // Payment Required
  403, // Forbidden
  404, // Not Found
  405, // Method Not Allowed
  406, // Not Acceptable
  407, // Proxy Authentication Required
  408, // Request Timeout // <<<<<<<<<<<<<<<<<<<<
  409, // Conflict
];

const defaultFailedAttemptHandler = (error: any) => {
  if (
    error.message.startsWith("Cancel") ||
    error.message.startsWith("TimeoutError") || // <<<<<<<<<<
    error.name === "TimeoutError" ||
    error.message.startsWith("AbortError") ||
    error.name === "AbortError"
  ) {
    throw error;
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if ((error as any)?.code === "ECONNABORTED") {
    throw error;
  }
  const status =
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (error as any)?.response?.status ?? (error as any)?.status;
  if (status && STATUS_NO_RETRY.includes(+status)) {
    throw error;
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if ((error as any)?.error?.code === "insufficient_quota") {
    const err = new Error(error?.message);
    err.name = "InsufficientQuotaError";
    throw err;
  }
};
```

However, reviewing OpenAI's documentation:

```
A `Timeout` error indicates that your request took too long to complete and our server closed the connection. This could be due to a network issue, a heavy load on our services, or a complex request that requires more processing time.
If you encounter a Timeout error, please try the following steps:

**Wait a few seconds and retry your request.** Sometimes, the network congestion or the load on our services may be reduced and your request may succeed on the second attempt.
Check your network settings and make sure you have a stable and fast internet connection. You may need to switch to a different network, use a wired connection, or reduce the number of devices or applications using your bandwidth.
If the issue persists, check out our persistent errors next steps section.
```

It _sounds_ like this should be retryable to me.

**Comment by wcummings** [comment] 2023-09-25 17:44
Going to try this out in my service, will make a PR if it solves my problem ^

**Comment by wcummings** [comment] 2023-09-25 20:32
Some more details here: https://github.com/openai/openai-node/blob/master/README.md#retries

```
Certain errors will be automatically retried 2 times by default, with a short exponential backoff. Connection errors (for example, due to a network connectivity problem), 408 Request Timeout, 409 Conflict, 429 Rate Limit, and >=500 Internal errors will all be retried by default.

You can use the maxRetries option to configure or disable this:
```

Maybe this is all we need, to increase maxRetries on the OAI client?

**Comment by stevenmilstein** [comment] 2023-09-28 02:13
@wcummings Thanks for hunting this down. Did that change solve the problem? If so, will you submit a PR?

**Comment by dhruv-anand-aintech** [comment] 2023-10-11 09:36
I just found out that retries are not happening at all, despite setting maxRetries to a valid value in the langchain ChatOpenAI object.

This sort of bug remaining unsolved for so long makes me doubt whether anyone uses langchainjs at all.

Can the maintainers fix this?

**Comment by getcreatr** [comment] 2023-10-24 12:44
+1 would like to see this implemented

**Comment by drewB** [comment] 2023-10-30 19:22
I can confirm I am seeing this same issue where no retry is happening even when I pass a maxRetries param.  Will have to switch to openAI's native lib which has this working until it is fixed.

**Comment by drewB** [comment] 2023-11-01 20:14
For anyone else following this issue, the change made in https://github.com/langchain-ai/langchainjs/issues/2706#issuecomment-1734422202 was to remove "TimeoutError" from the list of things not to retry.  I can confirm that does fix the issue.  That said, we can't just make that change to fix this because this handler is used for more than just openai.  

I notice there are many places where we explicitly set maxRetries to 0 in calls to the native openai lib.  Perhaps the best route would be to change that to use the maxRetries value for the langchain openai model?

**Comment by icelic** [comment] 2023-12-06 13:16
@codenameakshay what is the status of this PR that is supposed to fix maxRetries param not working?

**Comment by codenameakshay** [comment] 2023-12-06 15:00
> @codenameakshay what is the status of this PR that is supposed to fix maxRetries param not working?

The PR doesn't actually fix the bug as I discussed with @jacoblee93. It is still an open issue.

See https://github.com/langchain-ai/langchainjs/pull/3370#discussion_r1402660699

**Comment by jacoblee93** [comment] 2023-12-06 15:39
I do still really want to get to the bottom of it 😕 but yeah we need to differentiate between user defined timeouts, which probably shouldn't be retried as the user expects some resolution in a timeframe, vs OpenAI default timeouts.

**Comment by drewB** [comment] 2023-12-06 15:55
I am not following.  Why would the timeouts be different?  Seems like we are just dealing with a timeout value that has a default if the user doesn’t supply one.  Since OpenAI already handles retrying timeouts why do we need langchain to try and handle retries on timeouts as well? Couldn’t we just pass the user timeout value to OpenAI?

**Comment by drewB** [comment] 2023-12-06 16:22
Or maybe it is less about timeouts and more about retries.  Since OpenAI now handles retries in the library natively, seems like we should just let it do its thing rather than use a separate mechanism outside the library.

**Comment by drewB** [comment] 2023-12-06 19:27
If that was their desire won't they just setup retries to 0?

**Comment by icelic** [comment] 2023-12-06 20:48
Yeah but now maxRetries param is not working as expected so I think this is necessary change.

**Comment by adrienjoly** [comment] 2024-02-05 14:22
I'm surprised to see that the bot's suggestion above (https://github.com/langchain-ai/langchainjs/issues/2706#issuecomment-1732617130) was disliked that much.

It actually inspired us to come up with a working solution: extend `LangchainLLMChain` into a class that calls `withRetry()` (owned by one of its ancestor class: `Runnable`) every time we call `invoke`.

```js
class LLMChainWithRetry extends LangchainLLMChain {
    async call(values, config = undefined) {
        const runnableChain = super.withRetry({
            stopAfterAttempt: 3,
            onFailedAttempt: (error) => {
                if (error.name === 'TimeoutError') {
                    console.log(`[LLMChainWithRetry] Attempt ${error.attemptNumber} failed. There are ${error.retriesLeft} retries left.`);
                } else {
                    throw error;
                }
            }
        });
        return await runnableChain.invoke(values, config);
    }
}
```

**Comment by jacoblee93** [comment] 2024-02-05 19:02
Oh, you should also just pass `onFailedAttempt` where you'd be able to pass `maxRetries` and it would work as well. I don't think you'd need to subclass.

**Comment by jacoblee93** [comment] 2024-02-05 19:02
Closing for now given the above.

**Comment by SagefulAI** [comment] 2024-02-05 19:12
I don't understand why this is being closed.  Seems to me that there is still a clear bug here even if there is a workaround.

**Comment by jacoblee93** [comment] 2024-02-05 21:39
Because it's not clear what should be happening IMO

**Comment by drewB** [comment] 2024-02-09 18:31
Does anyone know how this is handled in the python version?  Could that perhaps guide us to a solution?

**Comment by wcummings** [comment] 2024-03-05 14:55
IMHO it is fine to make a breaking change and make this retryable. The timeout is not the same as a deadline, and if a request is retried for any other reason the total request time will exceed the timeout anyway.

**Comment by wcummings** [comment] 2024-03-05 15:13
Here's a draft of what I did in my codebase: https://github.com/langchain-ai/langchainjs/pull/4633

**Closed** 2024-03-05 19:50 UTC
Labels: auto:bug

**Comment by jacoblee93** [comment] 2024-03-05 19:55
Thanks for all your patience and especially @wcummings for the PR! New behavior will be live in the next core release (probably today).
