### ISSUE TITLE
Passing Pinecone.Index to PineconeStore.fromExistingIndex broken after update

### ISSUE THREAD

**Issue by dejoma** [langchain-ai/langchainjs#5686] opened 2024-06-06 13:20 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Package updates that trigger fail
If you update all pinecone/langchain packages to their latest versions:
```python
↑ @langchain/community 0.2.4 → 0.2.6
↑ @pinecone-database/pinecone 2.2.1 → 2.2.2
↑ langchain 0.2.4 → 0.2.5

# having @langchain/pinecone@0.0.7
```

### Code

Then the following code starts failing (in build-time):
```typescript
// My index with or without custom type; doesn't matter
const pinecone = new Pinecone();
const pineconeIndex = pinecone.Index<{
  helpMePlease: string;
}>('index-prod-eu');

const vectorStore = await PineconeStore.fromExistingIndex(embeddings, {
    pineconeIndex, // <- errors here
    namespace: 'i-say-whut-whut'
  });
```

### Error messages
Error with custom type:  
![image](https://github.com/langchain-ai/langchainjs/assets/48984220/54ddc5a4-0c3b-44f0-b15b-69f50b57fe28)  

Error without custom type:
![image](https://github.com/langchain-ai/langchainjs/assets/48984220/16a32313-c2aa-44c3-a584-2abf3ee8a452)

### Description

This is the code that works with the version numbers before upgrading.

### System Info

I am using bun 1.1.12
Node v20
Build fails

**Comment by jacoblee93** [comment] 2024-06-06 20:58
Closing as a duplicate of #5685

**Closed by jacoblee93** 2024-06-06 20:58 UTC
Labels: auto:bug
