### ISSUE TITLE
new Error("Please install chromadb as a dependency with, e.g. `npm install -S chromadb`") but chromadb existed in node_modules in newer langchain since version 147

### ISSUE THREAD

**Issue by helxsz** [langchain-ai/langchainjs#2637] opened 2023-09-14 23:47 UTC
My previous code used to be working in 0.0.145, 
```
import { CheerioWebBaseLoader } from "langchain/document_loaders/web/cheerio";
import { RecursiveCharacterTextSplitter } from "langchain/text_splitter";
import { HuggingFaceTransformersEmbeddings } from "langchain/embeddings/hf_transformers

const huggerEmbedding = new HuggingFaceTransformersEmbeddings({
  modelName: "Xenova/all-MiniLM-L6-v2",
});

import { Chroma } from "langchain/vectorstores/chroma";

const loader = new CheerioWebBaseLoader(
  "https://lilianweng.github.io/posts/2023-06-23-agent/"
);
const docs = await loader.load();

const splitter = new RecursiveCharacterTextSplitter({
  chunkOverlap: 0,
  chunkSize: 500,
});

const splitDocuments = await splitter.splitDocuments(docs);

const vectorStore = await Chroma.fromDocuments(splitDocuments, huggerEmbedding, {
  collectionName: "a-test-collection",
  url: "http://localhost:9007", // Optional, will default to this value
  collectionMetadata: {
    "hnsw:space": "cosine",
  }
});

const retrievedDocs = await vectorStore.similaritySearch(
  "What are the approaches to Task Decomposition?"
);
```

now in newer version, 0.0.147, 0.0.148, 0.0.149(not tested yet but seems to be still wrong) are all getting an errors saying 

```
node_modules/_langchain@0.0.147@langchain/dist/vectorstores/chroma.js:287
            throw new Error("Please install chromadb as a dependency with, e.g. `npm install -S chromadb`");
                  ^
Error: Please install chromadb as a dependency with, e.g. `npm install -S chromadb`
    at Function.imports (file:///Users/xisizhe/Documents/my_projects/langchain/lang147/node_modules/_langchain@0.0.147@langchain/dist/vectorstores/chroma.js:287:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Chroma.ensureCollection (file:///Users/xisizhe/Documents/my_projects/langchain/lang147/node_modules/_langchain@0.0.147@langchain/dist/vectorstores/chroma.js:89:42)
    at async Chroma.addVectors (file:///Users/xisizhe/Documents/my_projects/langchain/lang147/node_modules/_langchain@0.0.147@langchain/dist/vectorstores/chroma.js:126:28)
    at async Function.fromDocuments (file:///Users/xisizhe/Documents/my_projects/langchain/lang147/node_modules/_langchain@0.0.147@langchain/dist/vectorstores/chroma.js:262:9)
    at async file:///Users/xisizhe/Documents/my_projects/langchain/lang147/embedding_huggerface2.ts:31:21
```

however the node_modules has the latest chromadb 1.5.8 , even downgraded to 1.5.3, still output the same error for no reason, any ideas why chromadb package not found ?

**Comment by NajamShehzad** [comment] 2023-09-17 18:47
Getting same error while using chromadb 

![image](https://github.com/langchain-ai/langchainjs/assets/37629243/39353be4-381e-4c9a-9937-a2d0aea8ab7d)

**Comment by HenryHengZJ** [comment] 2023-09-18 11:41
bump, getting the same errors as well @jacoblee93 any idea?

**Comment by jacoblee93** [comment] 2023-09-18 13:51
Will have a look today, thanks for the heads up!

**Comment by pooriaarab** [comment] 2023-09-18 18:28
@jacoblee93 thx. Is there an ETA on when it can get fixed?

Currently Flowise is in production with Chroma and can't use it 🫠

**Comment by jacoblee93** [comment] 2023-09-18 19:00
@jeffchuber am about to dig in but any idea what could have changed?

We set our Chroma peer dep to `*`

**Comment by jacoblee93** [comment] 2023-09-18 19:09
@pooriaarab @NajamShehzad @HenryHengZJ @helxsz hard locking Chroma to `1.5.3` (no caret) fixed it for me:

`"chromadb": "1.5.3",`

If you add a caret it'll automatically upgrade to 1.5.9, which is likely where something bad was introduced.

@jeffchuber

**Comment by pooriaarab** [comment] 2023-09-18 19:11
@jacoblee93 thx for the quick update. 

this is from the Chroma discord:
https://discord.com/channels/1073293645303795742/1152647545122738286/1153294473690873906

Apparently, if you rhard lock and rollback to Chroma 1.5.6 it will work

**Comment by jacoblee93** [comment] 2023-09-18 19:52
Maybe if you go to 1.5.8?

**Comment by tazarov** [comment] 2023-09-18 20:11
Ideally, this would be fixed with https://github.com/chroma-core/chroma/pull/1153

Tested with LC@0.0.150

**Comment by jeffchuber** [comment] 2023-09-19 04:22
I just released `1.5.10` - thanks to @tazarov for the assistance. this temporarily removes the deps on `xeonova/transformers` and `webAI` until we can figure out how to package those libraries effectively

**Comment by jeffchuber** [comment] 2023-09-19 04:31
I confirmed with a minimal example that everything should be playing nice together - can folks give this a try?

**Comment by pooriaarab** [comment] 2023-09-19 15:46
@jeffchuber issue still exists. @tazarov mentioned 1.5.11 version of Chroma can fix the dependency errors.

**Comment by jacoblee93** [comment] 2023-09-19 19:54
Sounds like it fixed it! Thanks all for reporting - hopefully this doesn't happen again.

**Comment by martin-242** [comment] 2023-09-19 20:53
I have latest flowise and chroma 1.5.11 and it still showing the same error...

**Comment by jacoblee93** [comment] 2023-09-19 23:31
@jeffchuber any idea what's going on?

**Comment by jacoblee93** [comment] 2023-09-19 23:34
FWIW `langchain` + `chroma` seems to work for me with `npm`

**Comment by jacoblee93** [comment] 2023-09-25 15:37
Doesn't look like you're using it through LangChain?

We only support `@xenova/transformers` embeddings models right now:

https://js.langchain.com/docs/modules/data_connection/text_embedding/integrations/transformers

**Closed by jacoblee93** 2023-09-25 15:37 UTC
Labels: auto:bug

**Comment by helxsz** [comment] 2023-09-26 06:20
This is exact example I am testing right now.

```
import { pipeline, env } from '@xenova/transformers';
import * as fs from "fs"
env.localModelPath = '/Users/test/Desktop';
// @ts-ignore
env.allowRemoteModels = false;
env.backends.onnx.wasm.wasmPaths = '/Users/test/Desktop/Xenova/ort/';

import { HuggingFaceTransformersEmbeddings } from "langchain/embeddings/hf_transformers";

const model = new HuggingFaceTransformersEmbeddings({
  modelName: "Xenova/all-MiniLM-L6-v2",
});

/* Embed queries */
const res = await model.embedQuery(
  "What would be a good company name for a company that makes colorful socks?"
);
console.log({ res });
/* Embed documents */
const documentRes = await model.embedDocuments(["Hello world", "Bye bye"]);
console.log({ documentRes });
```
langchain 0.0147 can use the local model whereas langchain 0.0.150 looking to fetch the model from huggerface hub

**Comment by helxsz** [comment] 2023-09-26 06:55
This is exact example I am testing right now.

```
import { pipeline, env } from '@xenova/transformers';
import * as fs from "fs"
env.localModelPath = '/Users/test/Desktop';
// @ts-ignore
env.allowRemoteModels = false;
env.backends.onnx.wasm.wasmPaths = '/Users/test/Desktop/Xenova/ort/';

import { HuggingFaceTransformersEmbeddings } from "langchain/embeddings/hf_transformers";

const model = new HuggingFaceTransformersEmbeddings({
  modelName: "Xenova/all-MiniLM-L6-v2",
});

/* Embed queries */
const res = await model.embedQuery(
  "What would be a good company name for a company that makes colorful socks?"
);
console.log({ res });
/* Embed documents */
const documentRes = await model.embedDocuments(["Hello world", "Bye bye"]);
console.log({ documentRes });
```
langchain 0.0147 can use the local model whereas langchain 0.0.150 looking to fetch the model from huggerface hub

**Comment by ricardomatias** [comment] 2024-03-13 16:00
This is still happening with langchain (^0.1.27) and chromadb (^1.8.1).

```sh
Error: Please install chromadb as a dependency with, e.g. `npm install -S chromadb`
    at t.imports (file:///X/Projects/js/ai/live-llm/dist/index.js:238:10239)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.ensureCollection (file:///X/Projects/js/ai/live-llm/dist/index.js:238:7908)
    at async t.addVectors (file:///X/Projects/js/ai/live-llm/dist/index.js:238:8600)
    at async t.fromDocuments (file:///X/Projects/js/ai/live-llm/dist/index.js:238:9990)
    at async file:///X/Projects/js/ai/live-llm/dist/index.js:245:473
 ```

**Comment by jacoblee93** [comment] 2024-03-13 16:40
@bracesproul you were trying this recently weren't you?

**Comment by jacoblee93** [comment] 2024-03-13 16:44
Can you give me a bit of information about your environment @ricardomatias? It looks like it might be something like Next.js?

**Comment by george-sagaiq** [comment] 2024-12-19 04:12
Hi All - I know this issue is closed, but I recently came across this problem in December 2024 and found a fix/work-around for it. I was experiencing this issue when using LangChain's Chroma libraries for unit tests with testcontainers. Changing my npm test command from:
```
"test": "jest"
```
to:
```
"test": "node --experimental-vm-modules ../../node_modules/jest/bin/jest.js"
```

fixed the problem. Please note the `../../` is specific to the overall structure of my package layout in my nx-based project.

Here is a working jest test suite that uses testcontainers to spin up a chromadb instance, and then the test uses both the LangChain chroma abstractions in addition to the ChromaClient directly provided by the chroma team.

```typescript
import { ChromaDBContainer, StartedChromaDBContainer } from '@testcontainers/chromadb';
import { ChromaClient, OllamaEmbeddingFunction } from 'chromadb';
import { OllamaEmbeddings } from '@langchain/ollama';
import { PDFLoader } from '@langchain/community/document_loaders/fs/pdf';
import { Chroma } from '@langchain/community/vectorstores/chroma';
import { RecursiveCharacterTextSplitter } from 'langchain/text_splitter';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('path');

jest.setTimeout(10000);

const CHROMA_IMAGE = 'chromadb/chroma:0.5.18';

describe('chroma', () => {
  let chromaDbContainer: StartedChromaDBContainer | undefined = undefined;
  let chroma: ChromaClient | undefined = undefined;
  let chromaEmbeddingFunction: OllamaEmbeddingFunction | undefined = undefined;

  beforeAll(async () => {
    chromaDbContainer = await new ChromaDBContainer(CHROMA_IMAGE).start();

    chroma = new ChromaClient({
      path: `http://${chromaDbContainer.getHost()}:${chromaDbContainer.getMappedPort(8000)}`
    });

    chromaEmbeddingFunction = new OllamaEmbeddingFunction({
      url: `http://localhost:11434/api/embeddings`,
      model: 'nomic-embed-text'
    });
  });

  afterAll(async () => {
    if (chromaDbContainer) {
      await chromaDbContainer.stop();
    }
  });

  it('Just Works™', async () => {
    const documentPath = path.normalize('test-data/sample.pdf');
    const loader = new PDFLoader(documentPath, {
      splitPages: true
    });
    const textSplitter = new RecursiveCharacterTextSplitter({
      chunkSize: 300,
      chunkOverlap: 50
    });
    const doc = await loader.load();
    const splitDoc = await textSplitter.splitDocuments(doc);

    const ollamaEmbeddings = new OllamaEmbeddings({
      baseUrl: 'http://localhost:11434',
      model: 'nomic-embed-text'
    });

    const collectionName = 'test-collection';

    // ingest using the LangChain chroma abstraction
    await Chroma.fromDocuments(splitDoc, ollamaEmbeddings, {
      collectionName,
      url: `http://${chromaDbContainer.getHost()}:${chromaDbContainer.getMappedPort(8000)}`
    });

    // retrieve using the native chroma client
    const assistantCollection = await chroma.getCollection({ name: collectionName, embeddingFunction: chromaEmbeddingFunction });
    const collectionContents = await assistantCollection.get();
    expect(collectionContents.documents.length).toBe(93);
  });
});

```
